### ISSUE TITLE
我想问个问题啊

### ISSUE THREAD

**Issue by buzai** [leeenx/snake#1]
我用Canvas绘制贪吃的，每次贪吃蛇更新清空画布重新绘制出蛇和食物。但是会有一些闪烁，这个问题还好，最难受的是在每次吃食物的时候，判断吃到食物后我再去更新一个lable更新分数，竟然明显的卡顿了一下，这个可以避免么

**Comment by leeenx** [comment]
我在源码中没通过 `ticker` 来刷新舞台。如果您需要增加效果，可以把把更新舞台的任务放在 ticker 中，这样应该可以解决你说的问题。

ticker 的位置是：
https://github.com/leeenx/snake/blob/master/src/script/core/view.js#L233
把这里的注释去掉就可以了。

然后把下面这一行注释了，因为重复了
https://github.com/leeenx/snake/blob/master/src/script/core/view.js#L249 

如果还有您说的两个问题，可以跟我说一下。我本地测试一下。

**Comment by buzai** [comment]
@leeenx 谢谢了
