### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiamijun** [leeenx/snake#2]
1.经过一段时间后就没有食物了
2.使用键盘方向键控制上下时，浏览器整个窗口滚动条会上下滚动

**Comment by leeenx** [comment]
@xiamijun 

第一个问题能说明一下具体操作吗？
第二个问题是这样的，这个源码是针对移动端开发的，只是为了体验方便我加了键盘控制因为只是一个演示，所以并没有做太多细节处理。

**Comment by xiamijun** [comment]
按结束按钮重新开始有概率出现没有食物的情况，我怀疑是被上下左右的方向键盘给挡住了
![image](https://user-images.githubusercontent.com/11978184/33198490-5dd0466e-d126-11e7-8a4c-3e0a37d7da61.png)

**Comment by leeenx** [comment]
@xiamijun 应该是的。你是在电脑上看的对吧？因为这个项目的定位只是一个教程 demo，所以并没有做更多的适配。谢谢你的问题
