### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ForkKILLET** [leeenx/snake#3]
# 建议
***可以把蛇头换个颜色，便于识别*** 
*<-说说而已，不改也罢*
***还有就是蛇可以生成在固定的地方*** 
*<-第一次玩蛇头就正在墙上简直了*

**Comment by leeenx** [comment]
@ForkFG 
蛇头不同颜色以前没有考虑过，不过可以实现；
因为我玩过的贪吃蛇都是随机位置的，所以实现的时候选择了随机位置，不过直接撞死的问题确实是可能存在的。这个问题可以优化一下，谢谢您的建议
