### ISSUE TITLE
这个下载下来怎么直接用呢

### ISSUE THREAD

**Issue by myc404798846** [leeenx/snake#6]
我下载到了GitHub Desktop客户端里  不知道怎么运行可以玩一下

**Comment by leeenx** [comment]
@myc404798846 npm start 即可以运行。本地运行环境已经发布上线了

**Comment by solitudelyk** [comment]
大佬们，拿什么打开它

**Comment by leeenx** [comment]
> 

有 demo 地址：https://leeenx.github.io/snake/src/snake.html
